/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClearDialog: typeof import('./src/components/ClearDialog.vue')['default']
    CollapseColumnItem: typeof import('./src/components/CollapseItem/CollapseColumnItem.vue')['default']
    CollapseItem: typeof import('./src/components/CollapseItem/CollapseItem.vue')['default']
    CollapseRowItem: typeof import('./src/components/CollapseItem/CollapseRowItem.vue')['default']
    CutPointDialogueWrapper: typeof import('./src/components/ManualCutPoint/CutPointDialogueWrapper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileDragger: typeof import('./src/components/FileDragger.vue')['default']
    ManualCutPointView: typeof import('./src/components/ManualCutPoint/ManualCutPointView.vue')['default']
    PartialScreenshotView: typeof import('./src/components/PartialScreenshot/PartialScreenshotView.vue')['default']
    SavefileDialog: typeof import('./src/components/SavefileDialog.vue')['default']
    ScreenshotHelper: typeof import('./src/components/ScreenshotHelper.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  }
}
