name: Build and Publish Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel setuptools
          pip install aiohttp

      - name: Build Dev
        run: |
          python build/dev.py

      - name: Publish
        env:
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}
        run: |
          source venv/bin/activate
          python build/upload.py --dev
